### ISSUE TITLE
DataFlags should be int, in order to be used in Bass.ChannelGetData

### ISSUE THREAD

**Issue by UlyssesWu** [ManagedBass/ManagedBass.PInvoke#1]
In Bass.Net we can write:
`Bass.BASS_ChannelGetData(Channel, fft, (int)BASSData.BASS_DATA_FFT1024);`

But following code is wrong in ManagedBass:
`Bass.ChannelGetData(Channel, fft, (int)DataFlags.FFT1024);`
Since `DataFlags.FFT1024` is a uint type and it's value can not be converted to an int unless use `unchecked`:
`Bass.ChannelGetData(Channel, fft, unchecked((int)DataFlags.FFT1024));` <- right

In Bass.Net, this enum's type is int.

**Comment by MathewSachin** [comment]
Since, this might be (I'm not sure) a breaking change, so I'm not releasing this directly on NuGet.
